name: frontend
description: "RUPS flutter frontend"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  go_router: ^14.2.8
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  provider: ^6.1.2
  flutter_dotenv: ^5.1.0
  get_it: ^8.0.0
  url_launcher: ^6.3.0
  data_table_2: ^2.5.15
  json_annotation: ^4.9.0
  intl: any
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  json_serializable: ^6.8.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - .env